### PR TITLE
Release 0.8

### PR DESCRIPTION
**Pull request by christianbrodbeck**
@larsoner AFAIK no requirements changed, right?

### CODE REVIEW

**Comment by larsoner** [comment]
Yeah no new requirements

**Comment by christianbrodbeck** [comment]
Strange error on Appveyor: https://ci.appveyor.com/project/conda-forge/pysurfer-feedstock/build/1.0.7/job/sl5yfnxd8r82n8ho

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> Strange error on Appveyor: https://ci.appveyor.com/project/conda-forge/pysurfer-feedstock/build/1.0.7/job/sl5yfnxd8r82n8ho


re-rendering should fix it and the message above should take care of the re-rendering.

**Comment by christianbrodbeck** [comment]
Thanks!

**Pull request merged**
